import type { KeyDefinition, KeyId } from './types';

export const KEY_DEFINITIONS: KeyDefinition[] = [
  { id: 'ON', label: '', caption: 'ON', variant: 'system' },
  { id: 'HOME', label: 'HOME', caption: 'HOME', variant: 'system' },
  { id: 'SETTINGS', label: 'SETTINGS', caption: 'SETTINGS', variant: 'system' },
  { id: 'EXIT', label: 'EXIT', variant: 'system' },
  { id: 'MENU', label: 'MENU', variant: 'system' },
  { id: 'UP', label: '^', variant: 'nav' },
  { id: 'DOWN', label: 'v', variant: 'nav' },
  { id: 'LEFT', label: '<', variant: 'nav' },
  { id: 'RIGHT', label: '>', variant: 'nav' },
  { id: 'OK', label: 'OK', variant: 'nav' },
  { id: 'PAGEUP', label: '▲▲', variant: 'nav' },
  { id: 'PAGEDOWN', label: '▼▼', variant: 'nav' },
  { id: 'SHIFT', label: 'SHIFT', caption: 'SHIFT', variant: 'shift' },
  { id: 'ALPHA', label: 'A', caption: 'ALPHA', variant: 'alpha' },
  { id: 'VARIABLE', label: 'x', caption: 'VARIABLE', variant: 'default' },
  { id: 'FUNCTION', label: 'f(x)', caption: 'FUNCTION', variant: 'default' },
  { id: 'CATALOG', label: 'CATALOG', caption: 'CATALOG', shiftLabel: 'LIST', variant: 'default' },
  { id: 'TOOLS', label: 'TOOLS', caption: 'TOOLS', variant: 'default' },
  { id: 'X', label: 'x', shiftLabel: 'QR', variant: 'default' },
  { id: 'FRAC', label: 'a/b', shiftLabel: 'RECUR', variant: 'default' },
  { id: 'SQRT', label: '√', shiftLabel: 'ROOTN', variant: 'default' },
  { id: 'POWER', label: 'x□', shiftLabel: 'INV', variant: 'default' },
  { id: 'SQUARE', label: 'x²', shiftLabel: 'log', variant: 'default' },
  { id: 'LOG', label: 'log□', shiftLabel: 'ln', variant: 'default' },
  { id: 'ANS', label: 'Ans', shiftLabel: 'PREANS', variant: 'default' },
  { id: 'SIN', label: 'sin', shiftLabel: 'sin⁻¹', variant: 'default' },
  { id: 'COS', label: 'cos', shiftLabel: 'cos⁻¹', variant: 'default' },
  { id: 'TAN', label: 'tan', shiftLabel: 'tan⁻¹', variant: 'default' },
  { id: 'LPAREN', label: '(', shiftLabel: '=', variant: 'default' },
  { id: 'RPAREN', label: ')', shiftLabel: ',', variant: 'default' },
  { id: 'DEL', label: 'DEL', shiftLabel: 'INS', variant: 'default' },
  { id: 'AC', label: 'AC', shiftLabel: 'OFF', variant: 'default' },
  { id: 'SEVEN', label: '7', shiftLabel: 'π', variant: 'default' },
  { id: 'EIGHT', label: '8', shiftLabel: 'e', variant: 'default' },
  { id: 'NINE', label: '9', shiftLabel: 'i', variant: 'default' },
  { id: 'FOUR', label: '4', alphaLabel: 'A', variant: 'default' },
  { id: 'FIVE', label: '5', alphaLabel: 'B', variant: 'default' },
  { id: 'SIX', label: '6', alphaLabel: 'C', variant: 'default' },
  { id: 'ONE', label: '1', alphaLabel: 'D', variant: 'default' },
  { id: 'TWO', label: '2', alphaLabel: 'E', variant: 'default' },
  { id: 'THREE', label: '3', alphaLabel: 'F', variant: 'default' },
  { id: 'ZERO', label: '0', alphaLabel: 'x', variant: 'default' },
  { id: 'DOT', label: '.', alphaLabel: 'y', variant: 'default' },
  { id: 'EXP10', label: '×10□', alphaLabel: 'z', variant: 'default' },
  { id: 'FORMAT', label: 'FORMAT', shiftLabel: 'CYCLE', variant: 'default' },
  { id: 'EXE', label: 'EXE', shiftLabel: '≈', variant: 'exe' },
  { id: 'MULT', label: '×', shiftLabel: 'MIXED', variant: 'default' },
  { id: 'DIV', label: '÷', shiftLabel: '%', variant: 'default' },
  { id: 'PLUS', label: '+', shiftLabel: '°′″', variant: 'default' },
  { id: 'MINUS', label: '−', shiftLabel: '(−)', variant: 'default' },
];

export const KEYBOARD_MAP: Record<string, KeyId> = {
  '0': 'ZERO', '1': 'ONE', '2': 'TWO', '3': 'THREE', '4': 'FOUR',
  '5': 'FIVE', '6': 'SIX', '7': 'SEVEN', '8': 'EIGHT', '9': 'NINE',
  '.': 'DOT', '+': 'PLUS', '-': 'MINUS', '*': 'MULT', '/': 'DIV',
  'Enter': 'EXE', 'Escape': 'AC', 'Backspace': 'DEL',
  'ArrowUp': 'UP', 'ArrowDown': 'DOWN', 'ArrowLeft': 'LEFT', 'ArrowRight': 'RIGHT',
  '(': 'LPAREN', ')': 'RPAREN', '^': 'POWER',
  'PageUp': 'PAGEUP', 'PageDown': 'PAGEDOWN',
  'Home': 'HOME', 'End': 'EXIT',
  's': 'SHIFT', 'a': 'ALPHA', 'm': 'MENU',
  'Delete': 'DEL',
};

export function getKeyDefinition(id: KeyId): KeyDefinition | undefined {
  return KEY_DEFINITIONS.find((k) => k.id === id);
}
